import { Router } from 'express';
import adminRoutes from './modules/admin/routes/admin.routes.js';
import analyticsRoutes from './modules/analytics/routes/analytics.routes.js';
import auditRoutes from './modules/audit/routes/audit.routes.js';
import authRoutes from './modules/auth/routes/auth.routes.js';
import businessRoutes from './modules/businesses/routes/business.routes.js';
import chatRoutes from './modules/chat/routes/chat.routes.js';
import communityRoutes from './modules/communities/routes/community.routes.js';
import eventRoutes from './modules/events/routes/event.routes.js';
import feedRoutes from './modules/feed/routes/feed.routes.js';
import groupRoutes from './modules/groups/routes/group.routes.js';
import jobRoutes from './modules/jobs/routes/job.routes.js';
import marketplaceRoutes from './modules/marketplace/routes/marketplace.routes.js';
import mediaRoutes from './modules/media/routes/media.routes.js';
import notificationRoutes from './modules/notifications/routes/notification.routes.js';
import postRoutes from './modules/posts/routes/post.routes.js';
import reportRoutes from './modules/reports/routes/report.routes.js';
import searchRoutes from './modules/search/routes/search.routes.js';
import storyRoutes from './modules/stories/routes/story.routes.js';
import userRoutes from './modules/users/routes/user.routes.js';

const router = Router();

router.get('/health', (_req, res) => res.json({ status: 'ok', service: 'oned-social-api' }));
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/posts', postRoutes);
router.use('/businesses', businessRoutes);
router.use('/groups', groupRoutes);
router.use('/feed', feedRoutes);
router.use('/notifications', notificationRoutes);
router.use('/media', mediaRoutes);
router.use('/chat', chatRoutes);
router.use('/stories', storyRoutes);
router.use('/search', searchRoutes);
router.use('/reports', reportRoutes);
router.use('/admin', adminRoutes);
router.use('/marketplace', marketplaceRoutes);
router.use('/jobs', jobRoutes);
router.use('/events', eventRoutes);
router.use('/communities', communityRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/audit', auditRoutes);

export default router;
